apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: amnesia-shh
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    forceSTSHeader: true
    contentTypeNosniff: true
    frameDeny: true
    referrerPolicy: "no-referrer"
    permissionsPolicy: "geolocation=(), microphone=(), camera=()"
    customResponseHeaders:
      Cross-Origin-Embedder-Policy: "require-corp"
      Content-Security-Policy: "default-src 'self'; script-src 'self' https://cdn.tailwindcss.com; style-src 'self' https://fonts.googleapis.com https://cdn.jsdelivr.net 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://amnesia-shh.duckdns.org;"